spring:
  application:
    name: award
  datasource:
    url: jdbc:mysql://192.168.200.200:3306/ylottery?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.200.200
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /
    listener:
      simple:
        retry:
          max-attempts: 5
          enabled: true
          initial-interval: 5000ms

server:
  port: 10020
